<?php

namespace WCSBundle\Repository;

/**
 * giftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class giftRepository extends \Doctrine\ORM\EntityRepository
{
}
